import { colors, typography } from "@saleis-live/ui";
import { useEffect, useState } from "react";
import { Logo } from "./components/Logo";
import { resolveAssetUrl } from "./config/assets";
import { ADMIN_URL, DEMO_STORE_URL } from "./config/links";

const NAV_LINKS = [
  { label: "Product", href: "#product" },
  { label: "How it works", href: "#how-it-works" },
  { label: "Demo", href: "#demo" },
  { label: "Developers", href: "#developers" },
];

function useScrolled(threshold = 8): boolean {
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > threshold);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, [threshold]);
  return scrolled;
}

export function App() {
  const scrolled = useScrolled();

  return (
    <div style={styles.page}>
      <style>{`
        html { scroll-behavior: smooth; }
        .marketing-nav-links { display: flex; gap: 28px; }
        @media (max-width: 780px) { .marketing-nav-links { display: none; } }
        .marketing-hero-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 48px; align-items: center; }
        @media (max-width: 900px) { .marketing-hero-grid { grid-template-columns: 1fr; } }
        .marketing-steps { display: grid; grid-template-columns: repeat(3, 1fr); gap: 32px; }
        @media (max-width: 780px) { .marketing-steps { grid-template-columns: 1fr; } }
        .marketing-demo-cards { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }
        @media (max-width: 780px) { .marketing-demo-cards { grid-template-columns: 1fr; } }
      `}</style>

      <header style={{ ...styles.header, ...(scrolled ? styles.headerScrolled : {}) }}>
        <div style={styles.headerInner}>
          <a href="#product" style={styles.brand}>
            <Logo height={26} />
          </a>
          <nav className="marketing-nav-links">
            {NAV_LINKS.map((link) => (
              <a key={link.href} href={link.href} style={styles.navLink}>
                {link.label}
              </a>
            ))}
          </nav>
          <a href={ADMIN_URL} style={styles.navCta}>
            Get saleis.live
          </a>
        </div>
      </header>

      <section id="product" style={styles.hero}>
        <div className="marketing-hero-grid" style={styles.heroInner}>
          <div>
            <p style={styles.eyebrow}>PRODUCT</p>
            <h1 style={styles.h1}>Stock in. Sale live.</h1>
            <p style={styles.heroSub}>Turn unsold stock into a complete branded sale — powered by AI.</p>
            <div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginTop: 28 }}>
              <a href={ADMIN_URL} style={styles.primaryButton}>
                Get saleis.live
              </a>
              <a href="#demo" style={styles.secondaryButton}>
                View demo
              </a>
            </div>
            <p style={styles.heroFootnote}>No app to install to try it. No commission on what you sell. Your money never touches our accounts.</p>
          </div>
          <div style={styles.heroImageFrame}>
            <img src={resolveAssetUrl("/assets/hero/hero-laptop.png?v=3")} alt="A branded sale storefront generated by saleis.live" style={styles.heroImage} />
          </div>
        </div>
      </section>

      <section id="how-it-works" style={styles.section}>
        <p style={styles.eyebrowCenter}>HOW IT WORKS</p>
        <h2 style={styles.h2Center}>From a pile of stock to a live sale — three steps.</h2>
        <div className="marketing-steps" style={{ marginTop: 40 }}>
          <Step icon={<UploadIcon />} title="Upload stock" body="Excel, CSV, or just photos. Saleis.live handles the parsing and matching — no template to fight with." />
          <Step icon={<SparkleIcon />} title="AI prepares your catalogue" body="Cleans and enriches product data, suggests missing details, checks photos — you review and approve, nothing publishes unverified." />
          <Step icon={<StoreIcon />} title="Launch your sale" body="A branded storefront, on your own subdomain, ready to take real orders — payments and delivery connect through your own providers." />
        </div>
      </section>

      <section id="demo" style={{ ...styles.section, background: colors.paper }}>
        <p style={styles.eyebrowCenter}>DEMO</p>
        <h2 style={styles.h2Center}>See it running on real (fictional) data.</h2>
        <p style={styles.sectionSub}>
          The demo store below isn't saleis.live — it's proof of what saleis.live generates. Your own store, on your own subdomain, is what you get after "Get saleis.live".
        </p>
        <div className="marketing-demo-cards" style={{ marginTop: 32 }}>
          <a href={DEMO_STORE_URL} style={styles.demoCard}>
            <h3 style={styles.demoCardTitle}>View Demo Store →</h3>
            <p style={styles.demoCardBody}>The buyer side: a branded storefront generated from a sample catalogue — browse, bag, checkout.</p>
          </a>
          <a href={ADMIN_URL} style={styles.demoCard}>
            <h3 style={styles.demoCardTitle}>View Admin Demo →</h3>
            <p style={styles.demoCardBody}>The merchant side: upload stock, let AI prepare the catalogue, launch a sale, manage orders.</p>
          </a>
        </div>
      </section>

      <section id="developers" style={styles.section}>
        <p style={styles.eyebrowCenter}>DEVELOPERS</p>
        <h2 style={styles.h2Center}>Built as a platform, not a one-off shop build.</h2>
        <div style={styles.devGrid}>
          <div style={styles.devCard}>
            <h3 style={styles.devCardTitle}>Architecture</h3>
            <p style={styles.devCardBody}>
              A typed monorepo: shared domain types, a design-token package, an Express API, and separate React apps for the admin panel and each brand's storefront. Every business record carries a tenant and brand
              id — isolation is enforced at the data layer, not just the UI.
            </p>
          </div>
          <div style={styles.devCard}>
            <h3 style={styles.devCardTitle}>Payments &amp; delivery — bring your own integration</h3>
            <p style={styles.devCardBody}>
              Saleis.live never holds buyer funds and never sees a card number. Connect your own payment processor or courier by standing up a small bridge service against one fixed HTTP contract — no
              processor-specific SDK, no OAuth flow to build. Full request/response shapes are in Launch Studio's Payments and Delivery tabs once your store exists, and summarized below.
            </p>
            <pre style={styles.codeBlock}>
{`We call your endpoint:
POST  {endpointUrl}/checkout   { orderId, amountMinor, currency, returnUrl } → { checkoutUrl, ref }
GET   {endpointUrl}/status/{ref}                                            → { status }
POST  {endpointUrl}/refund     { ref, amountMinor, currency }               → { status }

Your service calls us back:
POST  https://saleis.live/api/webhooks/payment/{brandId}
      Header: X-Webhook-Secret: {your generated secret}
      Body:   { orderId, status, ref }`}
            </pre>
          </div>
          <div style={styles.devCard}>
            <h3 style={styles.devCardTitle}>Installable admin panel</h3>
            <p style={styles.devCardBody}>
              A per-brand installable app for the merchant side (your own name, icon, and colors on your home screen) is in progress. The buyer-facing storefront stays link-based by design — no install
              friction for someone who just wants to check out.
            </p>
          </div>
          <div style={styles.devCard}>
            <h3 style={styles.devCardTitle}>Deployment</h3>
            <p style={styles.devCardBody}>One Node API service, and one static site per app (admin, storefront, marketing), each independently deployable. Every brand resolves via its own subdomain, wildcard-routed to the same storefront build.</p>
          </div>
        </div>
      </section>

      <footer style={styles.footer}>
        <Logo height={16} />
        <span style={{ fontSize: 12, color: colors.muted }}>© {new Date().getFullYear()} saleis.live</span>
      </footer>
    </div>
  );
}

function Step({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) {
  return (
    <div>
      <div style={styles.stepIcon}>{icon}</div>
      <h3 style={styles.stepTitle}>{title}</h3>
      <p style={styles.stepBody}>{body}</p>
    </div>
  );
}

function UploadIcon() {
  return (
    <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke={colors.navy} strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 15V4M12 4l-4 4M12 4l4 4" />
      <path d="M4 16v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2" />
    </svg>
  );
}

function SparkleIcon() {
  return (
    <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke={colors.navy} strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 3v4M12 17v4M3 12h4M17 12h4" />
      <path d="M6 6l2.5 2.5M15.5 15.5L18 18M18 6l-2.5 2.5M8.5 15.5L6 18" />
    </svg>
  );
}

function StoreIcon() {
  return (
    <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke={colors.navy} strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
      <path d="M4 9l1-5h14l1 5" />
      <path d="M4 9a2 2 0 0 0 4 0 2 2 0 0 0 4 0 2 2 0 0 0 4 0 2 2 0 0 0 4 0" />
      <path d="M5 9v10h14V9" />
      <path d="M10 19v-6h4v6" />
    </svg>
  );
}

const styles: Record<string, React.CSSProperties> = {
  page: { fontFamily: typography.fontFamily.ui, color: colors.ink, background: colors.background },

  header: { position: "sticky", top: 0, zIndex: 10, background: "transparent", transition: "background 0.2s, box-shadow 0.2s" },
  headerScrolled: { background: colors.surface, boxShadow: "0 1px 0 rgba(0,0,0,0.06)" },
  headerInner: { maxWidth: 1200, margin: "0 auto", padding: "18px 32px", display: "flex", alignItems: "center", justifyContent: "space-between" },
  brand: { display: "flex", alignItems: "center", textDecoration: "none" },
  navLink: { fontSize: 14, fontWeight: 600, color: colors.ink, textDecoration: "none" },
  navCta: { fontSize: 13, fontWeight: 700, color: colors.white, background: colors.navy, padding: "10px 18px", borderRadius: 999, textDecoration: "none" },

  hero: { padding: "72px 32px 96px" },
  heroInner: { maxWidth: 1200, margin: "0 auto" },
  eyebrow: { fontSize: 12, fontWeight: 700, letterSpacing: 1, color: colors.navy, margin: "0 0 12px" },
  eyebrowCenter: { fontSize: 12, fontWeight: 700, letterSpacing: 1, color: colors.navy, margin: "0 0 12px", textAlign: "center" },
  h1: { fontFamily: typography.fontFamily.display, fontSize: 56, lineHeight: 1.05, margin: "0 0 20px" },
  h2Center: { fontFamily: typography.fontFamily.display, fontSize: 34, lineHeight: 1.2, margin: 0, textAlign: "center", maxWidth: 700, marginLeft: "auto", marginRight: "auto" },
  heroSub: { fontSize: 19, color: colors.muted, margin: 0, maxWidth: 460 },
  heroFootnote: { fontSize: 12, color: colors.muted, marginTop: 20, maxWidth: 460 },
  primaryButton: { display: "inline-block", background: colors.navy, color: colors.white, fontSize: 14, fontWeight: 700, padding: "14px 26px", borderRadius: 999, textDecoration: "none" },
  secondaryButton: { display: "inline-block", background: "transparent", color: colors.ink, fontSize: 14, fontWeight: 700, padding: "14px 26px", borderRadius: 999, textDecoration: "none", border: `1px solid ${colors.border}` },
  heroImageFrame: { position: "relative", aspectRatio: "1774 / 887", borderRadius: 16, overflow: "hidden", background: colors.paper },
  heroImage: { position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", objectPosition: "center bottom" },

  section: { padding: "80px 32px", maxWidth: 1200, margin: "0 auto" },
  sectionSub: { fontSize: 15, color: colors.muted, textAlign: "center", maxWidth: 620, margin: "16px auto 0" },

  stepIcon: { width: 52, height: 52, borderRadius: 12, background: colors.bluepale, display: "flex", alignItems: "center", justifyContent: "center", marginBottom: 16 },
  stepTitle: { fontSize: 17, fontWeight: 700, margin: "0 0 8px" },
  stepBody: { fontSize: 14, color: colors.muted, lineHeight: 1.6, margin: 0 },

  demoCard: { display: "block", background: colors.surface, border: `1px solid ${colors.border}`, borderRadius: 14, padding: 28, textDecoration: "none", color: colors.ink },
  demoCardTitle: { fontSize: 17, fontWeight: 700, color: colors.navy, margin: "0 0 8px" },
  demoCardBody: { fontSize: 14, color: colors.muted, lineHeight: 1.6, margin: 0 },

  devGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 24, marginTop: 40 },
  devCard: { background: colors.surface, border: `1px solid ${colors.border}`, borderRadius: 14, padding: 28 },
  devCardTitle: { fontSize: 16, fontWeight: 700, margin: "0 0 10px" },
  devCardBody: { fontSize: 13, color: colors.muted, lineHeight: 1.6, margin: 0 },
  codeBlock: { fontSize: 11, lineHeight: 1.6, background: colors.background, borderRadius: 8, padding: 14, marginTop: 14, overflowX: "auto", whiteSpace: "pre" },

  footer: { display: "flex", alignItems: "center", justifyContent: "center", gap: 16, padding: "32px", borderTop: `1px solid ${colors.border}` },
};
